MM-791 Added ConceptMap extension when applicable
Nictiz/Nictiz-STU3-Zib2017 pull request #116
Opened 2020-10-01 11:08 UTC by Stephanfur0re

2020-10-01 13:36 UTC, pieter-edelman-nictiz commented
@Stephanfur0re, boze schoomoeder hier: de pull request mag nooit direct naar stable-xxx gaan maar moet naar de release-branch. Aangezien die er nog niet is, heb ik de PR geconverteerd naar draft.

2020-10-05 08:13 UTC, ArdonToonstra reviewed
Every element has given a comment with the conceptmap as well, namely: "Use FHIR Core ConceptMap for HCIM mapping: [canonical URL]"

First of all, it states FHIR **Core** which for almost all is not the case. Secondly, I would place more empahsis on the mapping of values. 

How about: 
The ConceptMap [Name conceptmap] maps HCIM values to the required FHIR values. Please discuss this with someone in the team for a consistent good scentence.

2020-10-05 08:13 UTC, ArdonToonstra commented on Profiles - ZIB 2017/nl-core-humanname.xml
> +    </element>
This does not have to be added.

2020-10-05 08:25 UTC, ArdonToonstra requested changes
The changes can be made a lot more consistent and please double check you don't check-in stuff that is not part of the issue.

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-AdministrationSchedule.xml
> +      </binding>
I am missing a comment in the mappings

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-AdministrationSchedule.xml
>        <comment value="Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday. A ConceptMap (https://simplifier.net/resolve?canonical=http://nictiz.nl/fhir/ConceptMap/WeekdagCodelijst-to-days-
Should this be moved?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-AllergyIntolerance.xml
> +    </element>
Should we make the comment in the extension below consistent?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-AllergyIntolerance.xml
> +        <comment value="Severity. See for details the ConceptMap https://simplifier.net/resolve?target=simplifier&amp;canonical=http://nictiz.nl/fhir/ConceptMap/ErnstCodelijst-to-AllergyIntoleranceSe
Why the resolve functionality here? Please make this consistent

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-Encounter.xml
> +      <definition value="Defines a more specific coded value for a code or string. Especially useful for FHIR's required ValueSets. These extensions are primarily used on codes bound to a required va
What's this? Can be removed I guess.

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-Encounter.xml
>        <binding>
Are you sure you can delete this?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-GeneralMeasurement.xml
> -      <extension url="http://hl7.org/fhir/StructureDefinition/structuredefinition-display-hint">
Are you sure you want to delete this?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-LaboratoryTestResult-Observation.xml
> +  <version value="2.1.4" />
?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-LaboratoryTestResult-Observation.xml
> -  <purpose value="# Purpose of HCIM&#xD;&#xA;Laboratory tests are done for the purpose of diagnosing and preventing disease and follow-up on the effects of treatment." />
Why delete this?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-LaboratoryTestResult-Observation.xml
> +      <definition value="Measurements and simple assertions made about a patient, device or other subject. These may be a simple or a complex observations. Simple Observations could consist of just a
What's going on?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-LaboratoryTestResult-Observation.xml
> +      <comment value="This can either be the ZIB concept Test (NL-CM:13.1.4) or TestName (NL-CM:13.1.8) depending on the use of DiagnosticReport resource. This element shall be mapped to TestName if
I believe you have saved an older version...

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-LaboratoryTestResult-Observation.xml
> +          </extension>
De mapping.comment hier ook consisten meepakken?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-LaboratoryTestResult-Observation.xml
> +      <requirements value="Normally, an observation will have either a value or a set of related observations. A few observations (e.g. Apgar score) may have both a value and a set of related observa
No

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-LaboratoryTestResult-Observation.xml
> +      <fixedCode value="has-member" />
I don't believe this is part of the issue.

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-MedicationUse.xml
> +        <comment value="MedicationUseStopType.  See for details the ConceptMap (https://simplifier.net/resolve?canonical=http://nictiz.nl/fhir/ConceptMap/MedicationUseStopTypeCodeLijst-to-MedicationS
Why with the resolve functionality?

2020-10-05 08:25 UTC, ArdonToonstra commented on Profiles - ZIB 2017/zib-MedicationUse.xml
> +    <element id="MedicationStatement.dosage.dose[x]">
Not needed, can be removed.

2020-10-07 13:42 UTC, closed without merging