MM-1766 corrected the specialty by using practitionerrole extension
Nictiz/Nictiz-STU3-Zib2017 pull request #145
Opened 2021-02-10 09:49 UTC by eduardderijcke

Hi Vincent, could you please review my changes? Thanks!

2021-02-12 09:27 UTC, VincentGoris requested changes, later dismissed
Hi Eduard. Volgens mij is de wijziging nog niet volledig. Voor alle 3 de participants is er een foutieve rol. Dat betekend niet dat de rol verwijderd moet worden, maar moet worden aangepast naar 'verwijzer' of 'hoofdbehandelaar'. In ieder geval iets dat in de valueset past. Daarnaast lijkt het erop dat je de member hebt verwijderd, die moet blijven staan. De practitionerrole extensie moet komen onder participant.member. Dit moet voor alle 3 de participants gebeuren.

2021-02-12 11:28 UTC, eduardderijcke commented
@VincentGoris  Dank je wel voor je feedback, ik heb dit aangepast. Kan je dit nogmaals controleren en evt. goedkeuren?

2021-02-12 12:18 UTC, VincentGoris commented
Ik ga akkoord!

2021-02-12 13:33 UTC, eduardderijcke commented
@VincentGoris  Dank je wel voor het controleren. Wil jij dit nog 'officieel' goedkeuren (approved) in Github? Thanks!

2021-02-15 14:27 UTC, pieter-edelman-nictiz approved these changes

2021-02-15 14:33 UTC, merged