Added a purpose text element to Nictiz CapabilityStatements to indica…
Nictiz/Nictiz-STU3-Zib2017 pull request #172
Opened 2021-04-12 06:48 UTC by Stephanfur0re

Added a purpose text element to Nictiz CapababilityStatments

2021-04-12 10:21 UTC, niekvangalen requested changes
Ik zou er van maken:

This CapabilityStatement is informative in nature and does not represent the minimum or maximum set of capabilities your client or server should support. The aim is to design the CapabilityStatement as complete as possible, however for the exact set of capabilities the implementation guide of the corresponding information standard should be consulted.

Tevens moet dit ook worden aangepast in de git-repo's van BgZ, Images, Questionnaires en ik denk ook MedicationProcess, maar ik weet niet of wij daar zomaar in mogen klussen.

2021-04-12 11:40 UTC, ArdonToonstra commented
Mm, ik heb moete met dit zinsdeel: 'does not represent the minimum or maximum set of capabilities your client or server should support'. Het stelt toch namelijk wel het minimale voor?

Is dit wat?

`This CapabilityStatement describes the information standards desired capabilities in an informative manner. Every effort is made to ensure that the CapabilityStatement resources are correct and useful, but the normative set of capabilities is described in the implementation guide of the corresponding information standard.`

2021-04-12 12:46 UTC, pieter-edelman-nictiz commented
> 
> 
> Mm, ik heb moete met dit zinsdeel: 'does not represent the minimum or maximum set of capabilities your client or server should support'. Het stelt toch namelijk wel het minimale voor?
> 
Nee, volgens mij niet. We zeggen alleen dat de CS informatief is. In MM-1962 stond bv. echt een verkeerd profielen dat je niet hoefde te ondersteunen.

2021-04-12 13:35 UTC, Stephanfur0re commented
@pieter-edelman-nictiz, ben jij het dan ook eens met deze verwoording en PR? Zo ja, zou @niekvangalen de PR kunnen accorderen?

2021-04-12 13:57 UTC, ArdonToonstra commented
> We zeggen alleen dat de CS informatief is. 
Mee eens. Het beschrijft dus informatief de gewenste requirements/capabilities van een systeem. Ik bedenk me nu dat je optionele Resource types (zoals bijv. een optionele transactie zoals DocumentManifest) niet onder een minimale CapabilityStatement kan scharen zonder extensie.

2021-04-12 13:58 UTC, pieter-edelman-nictiz commented
Ik heb wat moeite met het woordje "your". Ik zou het hebben over "the server or client".

2021-04-12 14:04 UTC, Stephanfur0re commented
Dank Pieter en Ardon, ik zal "your client or server" wijzigen naar "the client or server"

2021-04-12 14:19 UTC, pieter-edelman-nictiz commented
Op de wiki staat die zinsnede geloof ik ook

2021-04-15 10:53 UTC, niekvangalen approved these changes

2021-04-19 12:12 UTC, pieter-edelman-nictiz requested changes
@Stephanfur0re het purpose-element is uiteindelijk weer weggehaald, deze pull request bevat alleen een datumverandering. Dat is vast niet de bedoeling :P

2021-04-19 12:18 UTC, Stephanfur0re commented
@pieter-edelman-nictiz , dat was inderdaad niet helemaal de bedoeling... ik heb de verwijdering van de purpose elementen reversed

2021-04-19 12:33 UTC, pieter-edelman-nictiz approved these changes

2021-04-19 12:33 UTC, merged