MM-1962: updated CapabilityStatements (client and server) for VitalSi…
Nictiz/Nictiz-STU3-Zib2017 pull request #175
Opened 2021-04-12 09:50 UTC by niekvangalen

…gns 2.x so they align with the corresponding FHIR IG

2021-04-12 09:50 UTC, niekvangalen commented
@pieter-edelman-nictiz  wil jij deze reviewen?

2021-04-12 11:45 UTC, pieter-edelman-nictiz reviewed
Zou de .date er niet ook uit kunnen?

2021-04-12 11:51 UTC, niekvangalen commented
@pieter-edelman-nictiz goed punt, dat laat ik Stephan in https://bits.nictiz.nl/browse/MM-1795 meenemen.

2021-04-12 12:00 UTC, pieter-edelman-nictiz requested changes
Graag ook nog de processing instructions weghalen, verder akkoord.

2021-04-15 08:13 UTC, niekvangalen commented
@pieter-edelman-nictiz .date velden bijgewerkt gezien kardinaliteit van 1..1, processing instructions weggehaald.

2021-04-16 06:46 UTC, pieter-edelman-nictiz approved these changes

2021-04-19 11:22 UTC, merged